import * as path from 'path';
import * as fs from 'fs';

export function generateDesignerCode(resxPath: string, resources: { [key: string]: { value: string; comment?: string } }, accessLevel: 'public' | 'internal' = 'public'): string {
    const existingSummaries = new Map<string, string>();

    // Try to read existing designer file
    const designerPath = resxPath.replace('.resx', '.Designer.cs');
    let existingNamespace: string | undefined;

    if (fs.existsSync(designerPath)) {
        const existingCode = fs.readFileSync(designerPath, 'utf8');
        const lines = existingCode.split('\n');
        let currentSummary = '';
        let inResourceProperty = false;
        let currentProperty = '';

        // Extract namespace if it exists
        const namespaceMatch = existingCode.match(/namespace\s+([^\s{]+)\s*{/);
        if (namespaceMatch) {
            existingNamespace = namespaceMatch[1];
        }

        for (let i = 0; i < lines.length; i++) {
            const line = lines[i].trim();

            // Check if we're entering a property definition
            if (line.includes('static string')) {
                inResourceProperty = true;
                const match = line.match(/static string (\w+)/);
                if (match) {
                    currentProperty = match[1];
                    // Only use the summary if we collected one and we're in a property
                    if (currentSummary && inResourceProperty) {
                        existingSummaries.set(currentProperty, currentSummary);
                    }
                }
            }
            // If we hit a closing brace, we're no longer in a property
            else if (line === '}') {
                inResourceProperty = false;
            }
            // Capture summary comments only when not already collecting one
            else if (line.startsWith('/// <summary>') && !currentSummary) {
                currentSummary = '';
                // Collect all summary lines until we see the end
                while (i < lines.length && !lines[i].trim().endsWith('</summary>')) {
                    currentSummary += lines[i] + '\n';
                    i++;
                }
                currentSummary += lines[i] + '\n'; // Add the </summary> line
            }
            // Reset summary if we're not in a property and hit another line
            else if (!inResourceProperty) {
                currentSummary = '';
            }
        }
    }

    const fileName = path.basename(resxPath, '.resx');
    // Use existing namespace if available, otherwise compute from filename
    const namespaceName = existingNamespace || (fileName.includes('.') ? fileName.split('.')[0] : 'Resources');
    const className = fileName.includes('.') ? fileName.split('.')[1] : fileName;

    let code = `//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ${namespaceName} {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("VS Code RESX Editor", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    ${accessLevel} class ${className} {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ${className}() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        ${accessLevel} static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("${namespaceName}.${className}", typeof(${className}).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        ${accessLevel} static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
`;

    // Generate a property for each resource
    for (const [key, resource] of Object.entries(resources)) {
        // Use existing summary if available, otherwise generate a new one
        if (existingSummaries.has(key)) {
            code += existingSummaries.get(key);
        } else {
            code += `        /// <summary>\n`;
            if (resource.comment) {
                code += `        ///   ${resource.comment}\n`;
            } else {
                code += `        ///   Looks up a localized string similar to ${resource.value}.\n`;
            }
            code += `        /// </summary>\n`;
        }
        code += `        ${accessLevel} static string ${key} {
            get {
                return ResourceManager.GetString("${key}", resourceCulture);
            }
        }
        
`;
    }

    code += `    }
}`;

    return code;
}